version: '3.8'

services:
  db:
    image:  postgres:14
    container_name: postgres   
    restart: always
    volumes:
      - ~/DOCKER/data/postgres:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  pg:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 1997estalyn@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ~/DOCKER/lib/pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    driver: bridge

