version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    volumes:
      - ~/DOCKER/data/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_URL: mongodb://root:pwd@mongo:27017/
    networks:
      - mongo
    depends_on:
      - mongo

networks:
  mongo:
    name: mongo
    driver: bridge